version: '3'
services:
#  openldap:
 #   image: osixia/openldap
#    container_name: openldap_web
#    command: --copy-service --loglevel debug
#    ports:
#      - "389:389"
#    volumes:
#      - ./bootstrapweb.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
#    environment:
#      LDAP_ORGANISATION: taxco
#      LDAP_ADMIN_PASSWORD: taxcoweb
#      LDAP_DOMAIN: shihadeh.intern
#      LDAP_BASE_DN: dc=shihadeh,dc=intern
#      KEEP_EXISTING_CONFIG: "false"
#      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
  openldap:
    image: osixia/openldap
    container_name: openldap_web
    command: --copy-service --loglevel debug
    ports:
      - "389:389"
    volumes:
      - ./boostrapwebtaxco.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      LDAP_ORGANISATION: taxco
      LDAP_ADMIN_PASSWORD: taxcoweb
      LDAP_DOMAIN: webtaxco.com
      LDAP_BASE_DN: dc=webtaxco,dc=com
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    networks:
      - web_authe
  webAuthentication:
    build:
      context: $webAuthenticationContext
      dockerfile: Dockerfile
    image: $webAuthenticationImage
    container_name: $webAuthenticationContainer
    ports:
      - '7091:7091'
    environment:
      SERVER_PORT: $webAuthenticationPort
      SERVER_PORT_TAXCO_EMAIL: $webTaxcoEmailPort
      MONGO_DB_URI: $mongoDbUri
    networks:
      - web_authe
  databaseMongo:
    image: $databaseMongoImage
    container_name: $databaseMongoContainer
    ports:
      - '27017:27017'
    volumes:
      - $databaseMongoVolumen
    networks:
      - web_authe
  webTaxcoApp:
    build:
      context: $webTaxcoAppContext
      dockerfile: Dockerfile
    image: $webTaxcoAppImage
    container_name: $webTaxcoAppContainer
    depends_on:
      - webTaxcoEureka
    ports:
      - '7090:7090'
    environment:
      SERVER_PORT: $webTaxcoAppPort
      SERVER_PORT_TAXCO_EMAIL: $webTaxcoEmailPort
      SERVER_PORT_WEB_AUTHE: $webAuthenticationPort
      MONGO_DB_URI: $mongoDbUri
      AWS_SECRET_KEY: $awsSecretKey
      AWS_ACCESS_KEY: $awsAccessKey
      AWS_BUCKET_NAME: $awsBucketName
    networks:
      - web_authe
  webGateway:
    build:
      context: $webGatewayContext
      dockerfile: Dockerfile
    image: $webGatewayImage
    container_name: $webGatewayContainer
    ports:
      - '7099:7099'
    environment:
      SERVER_PORT: $webGatewayPort
      SERVER_PORT_TAXCO_APP: $webTaxcoAppPort
      SERVER_PORT_WEB_AUTHE: $webAuthenticationPort
    networks:
      - web_authe
  webTaxcoEmail:
    build:
      context: $webTaxcoEmailContext
      dockerfile: Dockerfile
    image: $webTaxcoEmailImage
    container_name: $webTaxcoEmailContainer
    depends_on:
      - webTaxcoEureka
    ports:
      - '7092:7092'
    environment:
      SERVER_PORT: $webTaxcoEmailPort
      EMAIL_SENDER: $emailSender
      EMAIL_PASSWORD: $emailPassword
    networks:
      - web_authe
  webTaxcoEureka:
    build:
      context: $webTaxcoEurekaContext
      dockerfile: Dockerfile
    image: $webTaxcoEurekaImage
    container_name: $webTaxcoEurekaContainer
    ports:
      - '8761:8761'
    networks:
      - web_authe
#  web-front:
#    build:
#      context: $webTaxcoFrontContext
#      dockerfile: Dockerfile
#      args: [ "HOST_URL=http://187.227.238.91:8099"]
#    image: $webTaxcoFrontImage
#    environment:
#      host: $host
#    container_name: web-front
#    ports:
#      - '4300:80'
networks:
  web_authe: