version: '3'
services:
#  openldap:
 #   image: osixia/openldap
#    container_name: openldap_web
#    command: --copy-service --loglevel debug
#    ports:
#      - "389:389"
#    volumes:
#      - ./bootstrapweb.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
#    environment:
#      LDAP_ORGANISATION: taxco
#      LDAP_ADMIN_PASSWORD: taxcoweb
#      LDAP_DOMAIN: shihadeh.intern
#      LDAP_BASE_DN: dc=shihadeh,dc=intern
#      KEEP_EXISTING_CONFIG: "false"
#      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
  openldap:
    image: osixia/openldap
    container_name: openldap_web
    command: --copy-service --loglevel debug
    ports:
      - "389:389"
    volumes:
      - ./boostrapwebtaxco.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      LDAP_ORGANISATION: taxco
      LDAP_ADMIN_PASSWORD: taxcoweb
      LDAP_DOMAIN: webtaxco.com
      LDAP_BASE_DN: dc=webtaxco,dc=com
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    networks:
      - web_authe
  webAuthentication:
    build:
      context: $webAuthenticationContext
      dockerfile: Dockerfile
    image: $webAuthenticationImage
    container_name: $webAuthenticationContainer
    ports:
      - '8091:8091'
    networks:
      - web_authe
  databaseMongo:
    image: $databaseMongoImage
    container_name: $databaseMongoContainer
    ports:
      - '27017:27017'
    volumes:
      - $databaseMongoVolumen
    networks:
      - web_authe
  webTaxcoApp:
    build:
      context: $webTaxcoAppContext
      dockerfile: Dockerfile
    image: $webTaxcoAppImage
    container_name: $webTaxcoAppContainer
    ports:
      - '8090:8090'
    networks:
      - web_authe
  webGateway:
    build:
      context: $webGatewayContext
      dockerfile: Dockerfile
    image: $webGatewayImage
    container_name: $webGatewayContainer
    ports:
      - '8099:8099'
    networks:
      - web_authe
  webTaxcoEmail:
    build:
      context: $webTaxcoEmailContext
      dockerfile: Dockerfile
    image: $webTaxcoEmailImage
    container_name: $webTaxcoEmailContainer
    ports:
      - '8092:8092'
    networks:
      - web_authe
  web-front:
    build:
      context: $webTaxcoFrontContext
      dockerfile: Dockerfile
      args: [ "HOST_URL=http://187.227.238.91:8099"]
    image: $webTaxcoFrontImage
    environment:
      host: $host
    container_name: web-front
    ports:
      - '4300:80'
networks:
  web_authe: